steps:
  # 🧪 BUILD APP
  build:
    image: python:3.12-slim
    commands:
      - echo "🔧 Installing dependencies..."
      - apt-get update && apt-get install -y gcc && rm -rf /var/lib/apt/lists/*
      - echo "📦 Installing dependencies..."
      - pip install --timeout 1000 --retries 5 -r requirements.txt
      - echo "🏗️ Building app..."
      - python setup.py build || echo "No setup.py found, skipping..."
      - echo "✅ Build complete"

  # 🚀 DEPLOY APP
  deploy:
    image: docker:cli
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/daniel/deploy/asana:/mnt/deploy
    commands:
      - echo "🚀 Deploying app to host filesystem..."
      - echo "📁 Ensuring deploy directory exists..."
      - mkdir -p /mnt/deploy
      - echo "🧹 Stopping and removing old containers..."
      - docker stop asana || true
      - docker rm asana || true
      - echo "🗑️ Cleaning old files..."
      - rm -rf /mnt/deploy/* || true
      - echo "📦 Copying new files..."
      - cp -r ./* /mnt/deploy/
      - echo "📦 Running docker-compose from /mnt/deploy..."
      - docker compose -f /mnt/deploy/docker-compose.yml down || true
      - docker compose -f /mnt/deploy/docker-compose.yml up -d --build --force-recreate
      - echo "✅ Deployment complete!"

  # 🧹 CLEANUP
  cleanup:
    image: docker/compose:latest
    commands:
      - docker compose down --remove-orphans || true
      - docker system prune -f || true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      branch: master
