services:

  mcp_server:
    build: .
    container_name: mcp_server
    working_dir: /usr/src/app
    command: ./venv/bin/mcpo --port 7777 --api-key \$MCP_API_KEY -- ./venv/bin/python3 mcp_server.py;

    volumes:
      - /home/daniel/asana/data:/usr/src/app/data
    env_file:
      - .env

    restart: unless-stopped

    networks:
      - traefik-global
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.asana.rule=Host(`asana.sparktobloom.com`)"
      - "traefik.http.routers.asana.entrypoints=web"
      - "traefik.http.routers.asana.priority=100"
      - "traefik.http.services.asana.loadbalancer.server.port=7777"
      - "traefik.docker.network=traefik-global"

networks:
  traefik-global:
